		
			<div id="logo" class="column span-8">
				<h1>
					<a id="logo" accesskey="1" href="<?php echo $this->url(array(), 'default', true) ?>" title="Feedsnacks / Home"> 
          				<img alt="Feedsnacks.com" src="/images/logo.png" width="175" height="50" />    
  					</a> 
				</h1>
			</div>
			<div id="menu" class="column span-8">
				<?php echo 
				$this->navigation()
          			->menu()
          			->setulClass('');
				?> 
			</div>
			<div id="utilities" class="column span-8 last">
				<ul>
					<li><a href="<?php echo $this->url(array(), 'default', true) ?>" title="<?php echo $this->translate('Home') ?>"><?php echo $this->translate('Home') ?></a></li>
				</ul>				
			</div>
			<div id="breadcrumb" class="column span-24 last">
				<span>
				<?php echo 
				$this->navigation()
					->breadcrumbs()
					->setLinkLast(false)
          			->setSeparator(' &#9654;' . PHP_EOL); 
          		?>
          		&#9660; <a href="#main" title="<?php echo $this->translate('Skip To Content') ?>"><?php echo $this->translate('Skip') ?></a>
          		</span>
			</div>
		
		
		