<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?> 
<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headTitle() ?> 
    <?php echo $this->headMeta() ?> 
    <?php echo $this->headLink() ?> 
    <?php echo $this->headStyle() ?> 
    <?php echo $this->navigation()->links() ?> 
    <?php echo $this->dojo() ?> 
    <?php echo $this->headScript() ?>
</head>
<body class="nihilo">
	<div id="wrapper">
		<div id="header" class="container">
			<?php echo $this->render('_header.phtml') ?> 
		</div>
		<div id="main" class="container">
			<?php echo $this->layout()->content; ?>
			<?php $sidebar = $this->placeholder('sidebar'); ?>
    			<? if (count($sidebar)): ?>
  				<?php echo $sidebar; ?> 
  			<? endif; ?>
		</div>
		<div id="footer"  class="container">
			<?php echo $this->render('_footer.phtml') ?> 
		</div>
	</div> 
	<?php echo $this->inlineScript() ?> 

</body>
</html>
